Online_food_ordering/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('foodapp/',include("foodapp.urls")),
    path('', RedirectView.as_view(url='/foodapp/')), 
    path('accounts/',include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodapp/urls.py
from django.urls import path
from . import views

app_name = "foodapp"
urlpatterns = [
    path('',views.index,name="home"),
    path('login/', views.custom_login_view, name="login"),
    path('signup/', views.registration_view, name="signup"),
    path('logout/', views.CustomLogoutView.as_view(), name="logout"),
    path('add_restaurant/', views.AddRestaurant.as_view(),name="add_restaurant"),
    path('restaurant_list/', views.RestaurantList.as_view(),name="restaurant_list"),
]

foodapp/models.py
from django.db import models

# Create your models here.

class Restaurant(models.Model):
    restaurant_name = models.CharField(max_length=30)
    restaurant_image = models.ImageField(upload_to='media',default='')


    def __str__(self):
        return self.restaurant_name
    
class Food(models.Model):
    food_name = models.CharField(max_length=30)
    restaurants = models.ManyToManyField(Restaurant)
    food_image = models.ImageField(upload_to='media',default='')

    def __str__(self):
        return self.food_name

foodapp/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    contact = forms.CharField(max_length=15, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'contact', 'password1', 'password2']

foodapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LogoutView
from django.contrib import messages
from django.urls import reverse_lazy
from .models import Food, Restaurant
from django.views.generic import CreateView, ListView
from django.contrib.auth import authenticate, login

from django.urls import reverse_lazy
from .forms import RegistrationForm

# Create your views here.
def index(request):
    return render(request,'foodapp/index.html')

def custom_login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Login successful!')
                return redirect('foodapp:home')
            else:
                messages.error(request, 'Invalid username or password. Please try again.')
        else:
            messages.error(request, 'Invalid username or password. Please try again.')
    else:
        form = AuthenticationForm()

    return render(request, 'foodapp/login.html', {'form': form})

def registration_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been created successfully!')
            return redirect('foodapp:home')
        else:
            messages.error(request, 'There was an error in the form submission. Please correct the errors and try again.')
    else:
        form = RegistrationForm()

    return render(request, 'foodapp/signup.html', {'form': form})

class CustomLogoutView(LogoutView):
    def get_success_url(self):
        messages.success(self.request, 'Logout successful.')
        return reverse_lazy('foodapp:home')
    
class AddRestaurant(CreateView):
    model = Restaurant
    fields = '__all__'
    success_url = reverse_lazy("foodapp:restaurant_list")

class RestaurantList(ListView):
    model = Restaurant
    context_object_name = 'restaurant_list'

class AddFood(CreateView):
    model = Food
    fields = '__all__'
    success_url = reverse_lazy("foodapp:restaurant_list")

class FoodList(ListView):
    model = Food
    context_object_name = 'food_list'

foodapp/templates/foodapp/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
	{% load static %}
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/home_style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Caveat:700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bevan&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Caveat:400,700&subset=cyrillic" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <title>FOOD ZONE | Home</title>
	<link rel="shortcut icon" href="{% static 'images/favico.png' %}" type="image/x-icon">
  </head>
    <nav class="navbar navbar-expand-lg navbar-light" style="position: fixed;width:100%;background-image: linear-gradient(180deg,#FFF,#FFF);box-shadow: 0px 0px 7px 0px #404040;">
      <a class="navbar-brand" href="/"><h2 style="color:black;font-family:sans-serif;font-weight:bolder;"><b>FOOD ZONE</b></h2></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav" style="margin-left:auto!important;margin-right:30px;">
          <li class="nav-item active">
            <a class="nav-link" id="nav-link" href="{% url 'foodapp:home'%}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" id="nav-link" href="{% url 'foodapp:restaurant_list'%}">Restaurants <span class="sr-only">(current)</span></a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item active ml-auto">
                <a class="nav-link" id="nav-link" href="{% url 'logout'%}">Logout<span class="sr-only">(current)</span></a>
            </li>
          {% else %}
            <li class="nav-item active">
                <a class="nav-link" id="nav-link" href="{% url 'foodapp:login' %}">Login <span class="sr-only">(current)</span></a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <main>
      <div id="banner">
        <div id="banner-text">
            <h1>FOOD ZONE</h1>
            <p><b>Find your delicious hot food!</b></p>
        </div>
    </div>
    </main>
  </body>
</html>

foodapp/templates/foodapp/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    {% load static %}
    <meta charset="utf-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <style>
        .error-message {
            color: red;
            font-size: 20px;
        }
    </style>
    
</head>
<body>
    <div class="login-box">
        <h1>Login</h1>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form class="login-form" method="POST">
            {% csrf_token %}
            <div class="textbox">
                <i class="fas fa-user"></i>
                <label for="username">Username:</label>
                <input type="text" name="username" id="username" required>
            </div>

            <div class="textbox">
                <i class="fas fa-lock"></i>
                <label for="password">Password:</label>
                <input type="password" name="password" id="password" required>
            </div>
            <br>
            <div>
                <input type="submit" class="btn" style="color:white;" value="Login">
            </div>
        </form>
        <br>
        <div>
            <b> Don't Have Account ? &nbsp <a href="{% url 'foodapp:signup' %}" style="color: white;"> <span><u>Sign Up<u></span></a><b>
        </div>
    </div>
</body>
</html>

foodapp/templates/foodapp/restaurant_form.html
<main>
    <center><div class="middle-admin-reg">
      <center ><legend style="margin-top:25px;box-shadow:0px 3px 5px;width:50%;background:white;border-radius:25px;font-family: 'Courgette', cursive;">New Restaurant</legend></center>
      <div class="form-container">
        <form class="" action="addrestaurants" enctype="multipart/form-data" method="post">{% csrf_token %}
        <span class="entry-box">Restaurant Name : <input type="text" name="restaurant_name" placeholder="Eg: &quot;Dragon-Roll&quot;"></span>
        <span class="entry-box">Restaurant image : <input type="file" class="valid" name="restaurant_image" style="padding-left:0px" required/></span>
        <center><br/><button type="reset"class="butn" style="background-image: linear-gradient(190deg, rgba(183,28,28 ,1), rgba(239,154,154 ,1));" name="button">Cancel</button>
        &nbsp;&nbsp;<button type="submit"class="butn"  name="button">Add</button>
          </center>
        </form>
      </div>
    </div></center>
  </main>

foodapp/templates/foodapp/restaurant_list.html
{% comment %} {% load static %}
<main style="width:100%;margin-top: 0;margin-bottom: 10px;background-color:#FFF;">
    <div class="" style="max-width:100%;padding-top:20px;padding-bottom:20px;">
      <img class="mySlides" src="{% static 'images/image1.png' %}" height="400px" style="width:100%">
      {% comment %} <img class="mySlides" src="{% static 'images/slider2.jpg' %}" height="400px" style="width:100%">
      <img class="mySlides" src="{% static 'images/slider3.jpg' %}" height="400px" style="width:100%">
      <img class="mySlides" src="{% static 'images/slider4.jpg' %}" height="400px" style="width:100%"> {% endcomment %}
      {% comment %} <div class="" style="position:static;">
        {% for restaurant in restaurant_list %}
        <div class="card">
        <img src="{{restaurant.restaurant_image.url}}" alt="" style="height: 200px;width:100%;">
        <h1>{{restaurant.restaurant_name}}</h1>
        {% endfor %}
      </div>
    </div>
</main> {% endcomment %}


<div class="card">
    {% for restaurant in restaurant_list %}
    <img src="{{restaurant.restaurant_image.url}}" alt="{{restaurant.restaurant_image}}" style="height: 25%;width:25%;">
    <h1>{{restaurant.restaurant_name}}</h1> 
    {% endfor %}
</div>

foodapp/templates/foodapp/signup.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
  {% load static %}
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
  </head>
<body>
<div class="login-box" style="">
  <h1>Register Here</h1>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
  <form class="login-form" method="POST">
  {% csrf_token %}
  <div class="textbox">
    <i class="fas fa-user"></i>
    <label for="id_username">Username:</label>
    <input type="text" name="username" id="id_username" required>
  </div>

  <div class="textbox">
    <i class="fas fa-lock"></i>
    <label for="id_email">Email:</label>
    <input type="email" name="email" id="id_email" required>
  </div>

  <div class="textbox">
    <i class="fas fa-lock"></i>
    <label for="id_contact">Contact:</label>
    <input type="text" name="contact" id="id_contact" required>
  </div>

  <div class="textbox">
    <i class="fas fa-lock"></i>
    <label for="id_password1">Password:</label>
    <input type="password" name="password1" id="id_password1" required>
  </div>

  <div class="textbox">
    <i class="fas fa-lock"></i>
    <label for="id_password2">Confirm Password:</label>
    <input type="password" name="password2" id="id_password2" required>
  </div>

  <br>
  <div>
    <input type="submit" class="btn" style="color:white;" value="Register">
  </div> 
</form> 
  <br>
</div>
</body>
</html>